#!/usr/bin/env bash
# Install nginx web server and sample page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
