#!/usr/bin/env bash
# Configure Nginx server to /redirect_me will redirect to another page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=r7xIzV4rSbI permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx start
