#!/usr/bin/env bash
# Install nginx web server and sample page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
str_1="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
str_2="\n\tadd_header X-Served-By \$hostname;"
str_3="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$str_1$str_2$str_3/" /etc/nginx/sites-enabled/default
sudo service nginx start
