#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install haproxy -y
CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 1601-web-01 104.196.219.244:80 check
	server 1601-web-02 35.243.175.63:80 check
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy start
