#!/usr/bin/env bash
# script generates a MySQL dump and creates a compressed archive out of it
if [ $# -gt 0 ]
then
	PWD=$1
else
	PWD=""
fi

USER="root"

mysqldump --all-databases  -u=$USER -p$PWD > backup.sql

DATE=$(date +"%d-%m-Y")
tar -czf "$DATE".tar.gz backup.sql
