#!/usr/bin/env bash
# script that displays numbers from 1 to 100 in FizzBuzz fashion
i="0"
while [ $i -lt 100 ]
do
	((i++))
	if (( i%15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i%5 == 0 ))
	then
		echo "Buzz"
	elif (( i%3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
