#!/usr/bin/env bash
# displays Holberton School 10 times, for the 9th iteration Hi on a new line.
i="0"
while [ $i -lt 10 ]
do
	echo "Holberton School"
	((i++))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
