#!/usr/bin/env bash
# script that configures an Ubuntu server with
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/g ~/hosts.new
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
