#!/usr/bin/env bash
# script that configures the containerwith nginx user on port 8080
pkill -9 apache2
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
chmod 204 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
