#!/usr/bin/env bash
#replace listening port form 8080 to 80
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx restart
